name: deploy dev

on:
  push:
    branches: [main]

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::499202726088:role/GitHubActionsRole
          role-session-name: GithubActionsSession

      - name: npm ci
        run: npm ci

      # this provisions a temporary stage called 'dev-ci'
      - name: deploy temp environment
        run: npx sls deploy -s dev-ci --param="ssmStage=dev"

      # this generates the .env file for the 'dev-ci' stage
      - name: export env
        run: npx sls export-env --all -s dev-ci --param="ssmStage=dev"

      # apply seed data to dev-ci stage
      - name: add seed data
        run: node seed-restaurants.js

      # this runs the integration test against the 'dev-ci' stage
      # using the .env file that was captured earlier
      - name: run integration test
        run: npx cross-env TEST_MODE=handler jest

      # this runs the end-to-end test against the 'dev-ci' stage
      # using the .env file that was captured earlier
      - name: run end-to-end tests
        run: npx cross-env TEST_MODE=http jest

      # delete the 'dev-ci' stage
      - name: destroy temp environment
        run: npx sls remove -s dev-ci --param="ssmStage=dev"

      # deploy to the ACTUAL dev stage
      - name: deploy to dev
        run: npx sls deploy
